[package]
name = "learn_axum"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7"
axum-server = { version = "0.7" }

[dev-dependencies]
anyhow = "1"
httpc-test = { version = "0.1.1" }
