-- User
CREATE TABLE "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  username varchar(128) not null unique,
  -- auth 
  pwd varchar(256),
  pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
  token_salt uuid NOT NULL  DEFAULT gen_random_uuid()
);

-- Task
create table task (
  id bigint generated by default as identity (start with 1000) primary key,
  title varchar(256) not null
);