-- User
CREATE TABLE "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  username varchar(128) not null unique
);

-- Task
create table task (
  id bigint generated by default as identity (start with 1000) primary key,
  title varchar(256) not null
);